target 'Documentation' do
  platform :osx, '10.14'
  use_frameworks!

  pod "Bow", "~> 0.3.0"
  pod "BowEffects", "~> 0.3.0"
  pod "BowResult", "~> 0.3.0"
  pod "BowRx", "~> 0.3.0"
  pod "BowBrightFutures", "~> 0.3.0"
  pod "BowOptics", "~> 0.3.0"
  pod "BowGeneric", "~> 0.3.0"
  pod "BowRecursionSchemes", "~> 0.3.0"
  pod "BowFree", "~> 0.3.0"
end
