# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Prepare for release"
  lane :release  do |options|
    version_bump_podspec(path: "Bow.podspec", version_number: options[:version_number])
    add_git_tag(tag: options[:version_number], message: options[:description])
    push_git_tags
  end
end
